### ISSUE TITLE
IOS files

### ISSUE THREAD

**Issue by overinvest** [BitCodersNN/unn-mobile#160]
Добавьте файл для ios в релиз. На ios можно поставить приложение через sideloadly, но нужен файл чтобы установить его

**Comment by uf0logic** [comment]
Поддерживаю. Просто самостоятельно скомпилить пока что не получилось ¯\_(ツ)_/¯

**Comment by Namxobick** [comment]
Ок, в выходные гляну

**Comment by Namxobick** [comment]
Я так понял, что достаточно поменять расширение на .ipa
[ННГУ.zip](https://github.com/unn-mobile/unn-mobile/files/13692690/default.zip)

**Comment by overinvest** [comment]
Это же просто папка с файлами, а там единый файл ipa нужен

**Comment by Namxobick** [comment]
У это zip файла надо поменять расширение на .ipa и должно заработать, если верить гайду. (скинул zip, т.к. сюда нельзя скинуть .ipa)

**Comment by overinvest** [comment]
Сегодня попробую

**Comment by overinvest** [comment]
В общем не знаю, не получилось так сделать. Ошибку выдает при попытке установить

**Comment by Namxobick** [comment]
Не могу помочь, сам не пробовал) Я себе и еще одному человеку устанавливал через макбук, и приложение работало. 
Нам обещали предоставить аккаунт разработчика в App
Store. Надеемся, что в скором времени выложим в App Store

**Comment by overinvest** [comment]
У меня в целом есть мак, но не могу понять как собрать проект. У меня ошибки в каком-то файле, который связан с библиотеками

**Comment by Namxobick** [comment]
Можем в дс обсудить (namxobick)

**Comment by uf0logic** [comment]
Получилось установить через Trollstore, который вшивает прогу в систему, не требуя подписей. Через другие методы пока что ругается на профиль (См.Фото - там переименовал ННГУ в Payload, а ННГУ.app в UNN.app).  
![IMG_0962](https://github.com/unn-mobile/unn-mobile/assets/60444436/8a6e59cd-2642-4861-9028-5806ed07c562)

Щас тестить буду

**Comment by overinvest** [comment]
Получилось установить через sideloadly, надо было переименовать все что в зипке как ты сказал. 
ННГУ на Payload, а ННГУ.app в UNN.app
Закинул сюда файл уже готовый, надо просто разархивировать зипку
[test.zip](https://github.com/unn-mobile/unn-mobile/files/13726487/test.zip)

**Comment by overinvest** [comment]
Забавно что кроме расписания пока что ничего не реализовано 👯 Но все впереди! Молодцы ребята!!!

**Comment by Namxobick** [comment]
Мы в конце октября начали делать параллельно основной учебе) Физически не может выделять много времени( Также данный проект стал для нас знакомством с dart и flutter

**Comment by overinvest** [comment]
Я все понимаю, вы молодцы! Уверен, если продолжите этим заниматься, у вас все получится.
За время мини теста кстати, обнаружил пару визуальных недочетов. При пролистовании вкладок Лента, Расписание, Карта и Материалы и в целом, при переходи из 1 страницы на другую, предыдущая вкладка чуток подвисает в конце, после чего резко уходит в бок. Попробуйте использовать easeOutQuart анимацию
https://easings.net/ru#easeOutQuart

При нажатии в расписании на бокс с поиском выходит клавиатура и тд. Но когда закрываешь поиск, то есть нажимаешь на стрелку выйти, клавиатура остается. Это мешает полностью просмотреть страницу

Также надо добавить проверку какую-нибудь на сами вкладки, чтобы анимация открытия не показывалась постоянно.
Например нахожусь я на вкладке расписания и хочу вернуться на текущую неделю. Мне как новому пользователю интуитивно хочется снова тыкнуть на расписание и посмотреть расписание. После нажатия у меня снова появляется анимация, как будто я открыл вкладку расписания. Надо чтобы анимация была только если я пролистал например в самый низ, либо нахожусь на другой неделе, либо смотрю расписание группы/преподавателей
Также хочется чтобы предметы в расписании были кликабельны, то есть была возможность посмотреть например информацию, кто ведет предмет и тд.
На этом пока что все
