### ISSUE TITLE
Профиль(или фото) может оказаться null при загрузке приложения 

### ISSUE THREAD

**Issue by KriseevM** [BitCodersNN/unn-mobile#254]
Свежие крашрепорты говорят, что NullCheck на 67 строке в `loading_page_view_model.dart` иногда падает![Screenshot_2024-03-09-11-21-40-658_com.android.chrome.jpg](https://github.com/BitCodersNN/unn-mobile/assets/34946346/449187f7-6981-4e33-9096-cf0d103b415b)

**Comment by Namxobick** [comment]
DefaultCacheManager().downloadFile(profile!.fullUrlPhoto!);
Изображение может быть null, если пользователь не поставил своё изображение на профиль
