### ISSUE TITLE
EmployeeData, вероятно, больше не декодируется

### ISSUE THREAD

**Issue by KriseevM** [BitCodersNN/unn-mobile#255]
Ещё один любопытный репорт ссылается на (вероятно) отсутствие ключа в JSON EmployeeData при вызове fromJson на 49 строке
![Screenshot_2024-03-09-11-22-56-107_com.android.chrome.jpg](https://github.com/BitCodersNN/unn-mobile/assets/34946346/cd7cd4e9-66eb-4c26-95b0-7f818f367b70)

**Comment by Namxobick** [comment]
Без профиля сотрудника мы вряд ли найдем эту проблему =)
