### ISSUE TITLE
Получения файлов из живой ленты по id

### ISSUE THREAD

**Issue by Namxobick** [BitCodersNN/unn-mobile#272]

**Comment by dmitry-vnn** [comment]
К комменатрию/посту могут быть прикреплены файлы (если файл - изображение, на портале отображается в виде превью). Получить инфу о файле, такую как: название, размер проблематично, API битрикса, для работы с хранилищем шлёт куда-подальше за правами).
Но скачать файл/изображение, зная его id можно запросто
