### ISSUE TITLE
Snackbar с сообщением об отсутствии интернета (?)

### ISSUE THREAD

**Issue by KriseevM** [BitCodersNN/unn-mobile#286]
Думаю, может стоит вместо диалога с сообщением, что интернет пропал - показывать сообщение в виде плашки снизу ([snackbar](https://m2.material.io/components/snackbars))
Если это делать именно в таком режиме, то, по идее, можно достаточно просто решить и #242, и #243, но вопрос UX интересный. Стоит ли её, например, постоянно показывать или лучше прятать через секунды 3? Если второе - тогда #242 надо решать отдельно, чтобы не надо было перезаходить на вкладку для обновления, если первое - можно в этот snackbar приделать кнопку обновления и возможно будет норм

**Comment by Namxobick** [comment]
Если использовать snackbar, то я против того, чтобы он постоянно висел
